import Handlebars from 'handlebars';
type CompileOptions = Parameters<(typeof Handlebars)['compile']>[1];
export declare const makeHandlebars: (compileOptions?: CompileOptions) => typeof Handlebars;
export declare const makeHandlebarsWithHelpers: (helpers: Record<string, Handlebars.HelperDelegate>, compileOptions?: CompileOptions) => typeof Handlebars;
export declare const makeHtmlHandlebars: (compileOptions?: CompileOptions) => typeof Handlebars;
export declare const makeHtmlHandlebarsWithHelpers: (helpers: Record<string, Handlebars.HelperDelegate>, compileOptions?: CompileOptions) => typeof Handlebars;
export declare const makeHandlebarsRenderer: (template: string) => HandlebarsTemplateDelegate<any>;
export declare const renderHandlebars: (template: string, context: Record<string, unknown>) => string;
export declare const makeHtmlHandlebarsRenderer: (template: string) => HandlebarsTemplateDelegate<any>;
export declare const renderHtmlHandlebars: (template: string, context: Record<string, unknown>) => string;
export {};
